CREATE DATABASE IF NOT EXISTS `iskarmac_users`; USE `iskarmac_users`;

CREATE TABLE IF NOT EXISTS `gatekeeper` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `email` varchar(255) NOT NULL,
    `domain` varchar(255) NOT NULL,
    `verified` int(1) NOT NULL DEFAULT 0,
    `created` datetime NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`),
    UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `otp` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `otp` int(6) DEFAULT NULL,
    `type` int(1) DEFAULT NULL, /* 0 = gatekeeper,  1 = registered */
    `attempts` int(1) NOT NULL DEFAULT 0, /* max 4 attempts allowed */
    `date_issued` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), /* auto updates on resends */
    UNIQUE KEY `uid` (`uid`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sessions` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `session` varchar(255) DEFAULT NULL, /* session id generated by the server */
    `ip` varchar(45) DEFAULT NULL, /* ip addr of user */
    `country` varchar(120) DEFAULT NULL, /* country of user */
    `os` varchar(50) DEFAULT NULL, /*  */
    `os_version` varchar(50) DEFAULT NULL,
    `timezone` varchar(255) DEFAULT NULL,
    `browser` varchar(255) DEFAULT NULL,
    `browser_version` varchar(255) DEFAULT NULL,
    `method` varchar(255) DEFAULT NULL,
    `domain` varchar(255) DEFAULT NULL,
    `referrer` varchar(255) DEFAULT NULL,
    `agent` varchar(255) DEFAULT NULL,
    `speed` varchar(255) DEFAULT NULL,
    `device` varchar(255) DEFAULT NULL,
    `status` int(1) DEFAULT 0, /* show current login status */
    `login_time` datetime DEFAULT NULL,
    `logout_time` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `email` varchar(255) NOT NULL,
    `domain` varchar(255) NOT NULL,
    `created` datetime NOT NULL DEFAULT current_timestamp(),
    `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`),
    UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `kyc` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `email_alt` varchar(255) NULL,
    `firstname` varchar(255) NOT NULL DEFAULT 'enter your firstname',
    `lastname` varchar(255) NOT NULL DEFAULT 'enter your lastname',
    `gender` int(1) DEFAULT NULL,
    `dob` varchar(20) DEFAULT NULL,
    `phone` varchar(20) DEFAULT NULL,
    `id_type` varchar(255) DEFAULT NULL, /* citizenship, driving license, voters id, passport, pancard, aadhar card */
    `id_image` varchar(255) DEFAULT NULL,
    `id_kyc_status` int(1) DEFAULT 0,
    `id_address_proof` varchar(255) DEFAULT NULL, /* utility bill, bank statement, rent agreement, govt id */
    `id_address_proof_image` varchar(255) DEFAULT NULL, /* upload document max 2mb (pdf, jpeg, png) */
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `address` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `type` varchar(50) NULL, /* home / office / other */
    `primary` int(1) DEFAULT 0, /* 0 = not primary, 1 = primary */
    `label` varchar(50) NULL, /* nickname to identify multiple addresses */
    `address` varchar(255) NULL,
    `country` varchar(120) NULL,
    `state` varchar(120) NULL,
    `city` varchar(120) NULL,
    `zip` varchar(20) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `kyc_business` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `biz_name` varchar(255) DEFAULT NULL,
    `biz_type` varchar(255) DEFAULT NULL, /* select list of types of biz - manufacturing, services, retail etc. */
    `biz_industry` varchar(255) DEFAULT NULL, /* select list of types of industries - agri, solar, textile etc */
    `biz_category` varchar(255) DEFAULT NULL, /* select list of category based on industry*/
    `biz_reg_type` varchar(255) DEFAULT NULL, /* proprietorship, partnership, limted liability company, corporation, non-profit, co-operative */
    `biz_reg_cert` varchar(255) DEFAULT NULL, /* govt issued business registatration certificate */
    `biz_validity` varchar(255) DEFAULT NULL, /* validity of registatration as on certificate */
    `biz_annual_income` varchar(255) DEFAULT NULL, /* validity of certificate */
    `biz_total_employees` varchar(255) DEFAULT NULL, /* validity of certificate */
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `preferences` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `language` varchar(11) DEFAULT 0,
    `mode` int(1) DEFAULT 0,
    `timezone` int(1) DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `communication` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `status_newsletter` int(11) DEFAULT 0,
    `status_notifications` int(11) DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `security` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `uid` varchar(16) NOT NULL,
    `2factor` int(1) DEFAULT 0,
    `2factor_key` varchar(255) DEFAULT NULL,
    `status_terms` int(11) DEFAULT 0,
    `status_privacy` int(11) DEFAULT 0,
    `status_multisite` int(11) DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uid` (`uid`),
    UNIQUE KEY `2factor_key` (`2factor_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `select_list_options_json` ( /* build a tool to manage these fields and options */ /* json arrary of options */
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `biz_type` varchar(255) DEFAULT NULL,
    `biz_industry` varchar(255) DEFAULT NULL,
    `biz_category` varchar(255) DEFAULT NULL,
    `countries` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
